// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FOApi
{
    public partial class Tblcustomer
    {
        public Tblcustomer()
        {
            Tblorders = new HashSet<Tblorder>();
        }

        public int CustomerId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerMiddleName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerLandline { get; set; }
        public byte[] ProfileImage { get; set; }
        public string CustomerUsername { get; set; }
        public string CustomerPassword { get; set; }
        public int AccountStatus { get; set; }

        public virtual ICollection<Tblorder> Tblorders { get; set; }
    }
}