// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FOApi
{
    public partial class Tblmenutype
    {
        public Tblmenutype()
        {
            Tblmenus = new HashSet<Tblmenu>();
        }

        public int MenuTypeId { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Tblmenu> Tblmenus { get; set; }
    }
}