// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FOApi
{
    public partial class Tblrating
    {
        public int RatingId { get; set; }
        public int MenuId { get; set; }
        public int Score { get; set; }
        public string Remarks { get; set; }
        public DateTime DateRecorded { get; set; }
        public int CustomerId { get; set; }
    }
}