// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FOApi
{
    public partial class Tblsiteinfo
    {
        public int SiteInfoId { get; set; }
        public string SiteName { get; set; }
        public string Description { get; set; }
        public string ContactInfo { get; set; }
        public string Address { get; set; }
        public DateTime LastUpdate { get; set; }
        public int UserId { get; set; }
    }
}